/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SecureTransferVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimTransfer"
      | "createTransfer"
      | "nextTransferId"
      | "refundTransfer"
      | "transfers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TransferClaimed"
      | "TransferCreated"
      | "TransferRefunded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimTransfer",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createTransfer",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTransferId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transfers",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTransferId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfers", data: BytesLike): Result;
}

export namespace TransferClaimedEvent {
  export type InputTuple = [
    transferId: BigNumberish,
    recipient: AddressLike,
    secretHash: BytesLike
  ];
  export type OutputTuple = [
    transferId: bigint,
    recipient: string,
    secretHash: string
  ];
  export interface OutputObject {
    transferId: bigint;
    recipient: string;
    secretHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferCreatedEvent {
  export type InputTuple = [
    transferId: BigNumberish,
    sender: AddressLike,
    recipient: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    secretHash: BytesLike,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    transferId: bigint,
    sender: string,
    recipient: string,
    token: string,
    amount: bigint,
    secretHash: string,
    deadline: bigint
  ];
  export interface OutputObject {
    transferId: bigint;
    sender: string;
    recipient: string;
    token: string;
    amount: bigint;
    secretHash: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRefundedEvent {
  export type InputTuple = [transferId: BigNumberish, sender: AddressLike];
  export type OutputTuple = [transferId: bigint, sender: string];
  export interface OutputObject {
    transferId: bigint;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecureTransferVault extends BaseContract {
  connect(runner?: ContractRunner | null): SecureTransferVault;
  waitForDeployment(): Promise<this>;

  interface: SecureTransferVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimTransfer: TypedContractMethod<
    [transferId: BigNumberish, secret: string],
    [void],
    "nonpayable"
  >;

  createTransfer: TypedContractMethod<
    [
      recipient: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      secretHash: BytesLike,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  nextTransferId: TypedContractMethod<[], [bigint], "view">;

  refundTransfer: TypedContractMethod<
    [transferId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transfers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, bigint, bigint] & {
        sender: string;
        recipient: string;
        token: string;
        amount: bigint;
        secretHash: string;
        deadline: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimTransfer"
  ): TypedContractMethod<
    [transferId: BigNumberish, secret: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTransfer"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      secretHash: BytesLike,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextTransferId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "refundTransfer"
  ): TypedContractMethod<[transferId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transfers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, string, bigint, bigint] & {
        sender: string;
        recipient: string;
        token: string;
        amount: bigint;
        secretHash: string;
        deadline: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TransferClaimed"
  ): TypedContractEvent<
    TransferClaimedEvent.InputTuple,
    TransferClaimedEvent.OutputTuple,
    TransferClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TransferCreated"
  ): TypedContractEvent<
    TransferCreatedEvent.InputTuple,
    TransferCreatedEvent.OutputTuple,
    TransferCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRefunded"
  ): TypedContractEvent<
    TransferRefundedEvent.InputTuple,
    TransferRefundedEvent.OutputTuple,
    TransferRefundedEvent.OutputObject
  >;

  filters: {
    "TransferClaimed(uint256,address,bytes32)": TypedContractEvent<
      TransferClaimedEvent.InputTuple,
      TransferClaimedEvent.OutputTuple,
      TransferClaimedEvent.OutputObject
    >;
    TransferClaimed: TypedContractEvent<
      TransferClaimedEvent.InputTuple,
      TransferClaimedEvent.OutputTuple,
      TransferClaimedEvent.OutputObject
    >;

    "TransferCreated(uint256,address,address,address,uint256,bytes32,uint64)": TypedContractEvent<
      TransferCreatedEvent.InputTuple,
      TransferCreatedEvent.OutputTuple,
      TransferCreatedEvent.OutputObject
    >;
    TransferCreated: TypedContractEvent<
      TransferCreatedEvent.InputTuple,
      TransferCreatedEvent.OutputTuple,
      TransferCreatedEvent.OutputObject
    >;

    "TransferRefunded(uint256,address)": TypedContractEvent<
      TransferRefundedEvent.InputTuple,
      TransferRefundedEvent.OutputTuple,
      TransferRefundedEvent.OutputObject
    >;
    TransferRefunded: TypedContractEvent<
      TransferRefundedEvent.InputTuple,
      TransferRefundedEvent.OutputTuple,
      TransferRefundedEvent.OutputObject
    >;
  };
}
